# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Additional_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('install_num_from_own_website', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('current_version', models.IntegerField(blank=True, default=0, null=True)),
                ('additional_info1', models.CharField(max_length=500)),
                ('additional_info2', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='APKDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('title_shortcode', models.CharField(max_length=30)),
                ('devloper', models.CharField(max_length=50)),
                ('ratting', models.IntegerField(blank=True, default=0, null=True)),
                ('offers_in_app', models.CharField(max_length=30)),
                ('play_store_download_link', models.CharField(max_length=500)),
                ('apkpure_download_link', models.CharField(max_length=500)),
                ('apk_version', models.CharField(max_length=30)),
                ('description_1', models.CharField(max_length=1000)),
                ('description_2', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('added_on', models.DateField(auto_now_add=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('number_of_install', models.IntegerField(blank=True, default=0, null=True)),
                ('required_android_version', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('additional_info', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.Additional_info')),
            ],
        ),
        migrations.CreateModel(
            name='APKSubDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=50)),
                ('title_shortcode', models.CharField(max_length=30)),
                ('devloper', models.CharField(max_length=50)),
                ('ratting', models.IntegerField(blank=True, default=0, null=True)),
                ('offers_in_app', models.CharField(max_length=30)),
                ('play_store_download_link', models.CharField(max_length=500)),
                ('apkpure_download_link', models.CharField(max_length=500)),
                ('apk_version', models.CharField(max_length=30)),
                ('description_1', models.CharField(max_length=1000)),
                ('description_2', models.CharField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image1', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image2', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image3', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image4', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('image5', models.FileField(blank=True, null=True, upload_to=b'apkimage')),
                ('added_on', models.DateField(auto_now_add=True, null=True)),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('number_of_install', models.IntegerField(blank=True, default=0, null=True)),
                ('required_android_version', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('additional_info', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.Additional_info')),
                ('apkdetails', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.APKDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now_add=True, null=True)),
                ('comments', models.CharField(max_length=1000)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
                ('apkdetails', models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.APKDetails')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('status', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='category',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.Category'),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.SubCategory'),
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='category',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.Category'),
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='subcategory',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.SubCategory'),
        ),
    ]
