# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apkdetails',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='apksubdetails',
            name='additional_info',
        ),
        migrations.AddField(
            model_name='additional_info',
            name='apkdetails',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.APKDetails'),
        ),
        migrations.AddField(
            model_name='additional_info',
            name='apksubdetails',
            field=models.ForeignKey(blank=True, default=b'', null=True, on_delete=django.db.models.deletion.CASCADE, to='apkstore.APKSubDetails'),
        ),
    ]
