# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0002_auto_20180315_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b'django_project/static/img'),
        ),
    ]
