# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-15 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0003_auto_20180315_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='additional_info1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='additional_info',
            name='additional_info2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='apk_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='apkpure_download_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='devloper',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='offers_in_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='play_store_download_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='apk_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='apkpure_download_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='devloper',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='image5',
            field=models.FileField(blank=True, null=True, upload_to=b'apkimage'),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='offers_in_app',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='play_store_download_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
