# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0004_auto_20180315_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional_info',
            name='current_version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='apk_version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='ratting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='required_android_version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='apk_version',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='ratting',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='required_android_version',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
