# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-16 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0005_auto_20180316_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apkdetails',
            name='apk_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='apk_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
