# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-22 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0007_auto_20180316_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='app_upload_file',
            field=models.FileField(blank=True, null=True, upload_to=b'apkfile'),
        ),
    ]
