# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 19:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0012_auto_20180420_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='description_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='description_3',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
