# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0013_auto_20180420_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apkdetails',
            old_name='apk_hostgetor_url',
            new_name='apk_url',
        ),
        migrations.RenameField(
            model_name='apksubdetails',
            old_name='apk_hostgetor_url',
            new_name='apk_url',
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='description_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='description_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='description_4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='description_5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apkdetails',
            name='description_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='apksubdetails',
            name='description_3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
