# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0014_auto_20180420_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apkdetails',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='apkdetails',
            name='img_url_6',
        ),
        migrations.RemoveField(
            model_name='apksubdetails',
            name='description_5',
        ),
        migrations.RemoveField(
            model_name='apksubdetails',
            name='img_url_6',
        ),
    ]
