# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-19 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0015_auto_20180420_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
