# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0016_auto_20180420_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='required_version',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='required_version',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
