# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-21 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0017_auto_20180421_2112'),
    ]

    operations = [
    ]
