# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-22 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0018_auto_20180421_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='meta_description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='meta_keyword',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apkdetails',
            name='page_title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='meta_description',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='meta_keyword',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='page_title',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='category_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='category_our_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='meta',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_id',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category_our_name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='meta',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
