# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0020_auto_20180428_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='app_url_show',
            field=models.CharField(default=0, max_length=1000),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='app_url_show',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
