# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0021_auto_20180428_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='apkdetails',
            name='img_url_6',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='apksubdetails',
            name='img_url_6',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
    ]
