# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0022_auto_20180428_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateField(auto_now_add=True, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description_1', models.CharField(blank=True, max_length=2000, null=True)),
                ('description_2', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_desc', models.CharField(blank=True, max_length=2000, null=True)),
                ('meta_keyword', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
