# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0023_auto_20180503_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='image_link',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
    ]
