# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0024_auto_20180506_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='blog_url',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articleblog',
            name='page_title',
            field=models.CharField(blank=True, default=0, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='articleblog',
            name='short_code',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
