# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0025_auto_20180507_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
