# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-10 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0026_auto_20180510_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='desc_short',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
