# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apkstore', '0027_auto_20180510_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleblog',
            name='div_id',
            field=models.CharField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
